In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

In [2]:
""" Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables. """
#Ans:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


In [3]:
""" Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list."""
#Ans:
def Data_type(x):
    for i in x:
        print(type(i))
Data_type(list_)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [4]:
Data_type(array_list)

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
"""Q3. Considering the following changes in the variable, array_list:"""
array_list = np.array(object = list_, dtype = int)
"""Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list."""
#Ans: Yes, there will be change as data-type of elemensts in array_list will of int as it is exp[lictly changed.

Data_type(list_)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
Data_type(array_list)

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
"""Consider the below code to answer further questions:"""
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [12]:
""" Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size """
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
num_array.shape

(2, 3)

In [14]:
num_array.size

6

In [18]:
""" Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function."""
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
""" Q6. Create an identity matrix of shape (5,5) using numpy functions?"""
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])